### ISSUE TITLE
IOPub data rate exceeded.

### ISSUE THREAD

**Issue by rahulbordoloi** [googlecolab/open_in_colab#7]
How do I Rectify this in Google Colab?

The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

**Comment by RazRodrigues** [comment]
olá!
Saudações pessoal!
estou tendo com dificuldade de encontrar solução para um problema  no Google Colab + GEE.
se trata de uma análise de NDVI (pelo colab) para avaliar as médias mensais em uma serie temporal.
Fiz um "print()" de um dos resultados e aparece essa mensagem
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

E Quando tento  adicionar o layer dos resultado por meio do  "Map.addLayer"(...) dá erro... 
Será que alguém pode me dar uma ajuda?

**Comment by peap** [comment]
For general issues with Colab, please use https://github.com/googlecolab/colabtools/issues.
